const modelSItem = [
    {
        img: '/images/model-s-plaid-func.jpg',
        heading: 'Model S',
        desc: 'Dual Motor All-Wheel Drive unlocks more range than any other vehicle in our current lineup, with insane power and maximum control.',
        unit1: '3.1 s',
        unit2: '405 mi',
        unit3: '670 hp',
        bottomUnit1: '0-60 mph',
        bottomUnit2: 'Range (EPA est.)',
        bottomUnit3: 'Peak Power',
    },
    {
        img: '/images/model-s-func.jpg',
        heading: 'Model S Plaid',
        desc: 'Maintain 1,000+ horsepower all the way to 200 mph with Tri-Motor All-Wheel Drive, featuring torque vectoring and three independent carbon-sleeved rotors.',
        unit1: '1.99 s*',
        unit2: '396 mi',
        unit3: '1,020 hp',
        bottomUnit1: '0-60 mph',
        bottomUnit2: 'Range (EPA est.)',
        bottomUnit3: 'Peak Power',
    },
]

export const modelSItems = [
    {
        img: '/images/customModal-s/model-s-plaid-func-mobile.jpg',
        heading: 'Model S',
        desc: 'Dual Motor All-Wheel Drive unlocks more range than any other vehicle in our current lineup, with insane power and maximum control.',
        unit1: '3.1 s',
        unit2: '405 mi',
        unit3: '670 hp',
        bottomUnit1: '0-60 mph',
        bottomUnit2: 'Range (EPA est.)',
        bottomUnit3: 'Peak Power',
    },
    {
        img: '/images/customModal-s/model-s-func-mobile.jpg',
        heading: 'Model S Plaid',
        desc: 'Maintain 1,000+ horsepower all the way to 200 mph with Tri-Motor All-Wheel Drive, featuring torque vectoring and three independent carbon-sleeved rotors.',
        unit1: '1.99 s*',
        unit2: '396 mi',
        unit3: '1,020 hp',
        bottomUnit1: '0-60 mph',
        bottomUnit2: 'Range (EPA est.)',
        bottomUnit3: 'Peak Power',
    },
]

export const spec = [
    {
        headingLeftOne: 'Range (EPA est.)',
        headingLeftTwo: '1/4 Mile',
        headingLeftThree: 'Peak Power',
        headingLeftFour: 'Wheels',
        headingLeftFive: 'Cargo',
        headingLeftSix: 'Weight',
        unitLeftOne: '396 mi',
        unitLeftTwo: '9.23@155 mph trap speed',
        unitLeftThree: '1,020 hp',
        unitLeftFour: '19" or 21"',
        unitLeftFive: '28 cu ft',
        unitLeftSix: '4,766 lbs',
        headingRighttOne: '*Acceleration',
        headingRighttTwo: '†Top Speed',
        headingRighttThree: 'Drag Coefficient',
        headingRighttFour: 'Powertrain',
        headingRighttFive: 'Supercharging Max',
        unitRighttOne: '1.99 s 0-60 mph with rollout subtracted',
        unitRighttTwo: '200 mph when equipped with paid hardware upgrades',
        unitRighttThree: '0.208 Cd',
        unitRighttFour: 'Tri Motor',
        unitRighttFive: '250 kW',
    },
    {
        headingLeftOne: 'Range (EPA est.)',
        headingLeftTwo: 'Peak Power',
        headingLeftThree: 'Wheels',
        headingLeftFour: 'Cargo',
        headingLeftFive: 'Acceleration',
        unitLeftOne: '405 mi',
        unitLeftTwo: '670 hp',
        unitLeftThree: '19" or 21"',
        unitLeftFour: '28 cu ft',
        unitLeftFive: '3.1 s 0-60 mph',
        headingRighttOne: 'Top Speed',
        headingRighttTwo: 'Drag Coefficient',
        headingRighttThree: 'Weight',
        headingRighttFour: 'Powertrain',
        headingRighttFive: 'Supercharging Max',
        unitRighttOne: '149 mph',
        unitRighttTwo: '0.208 Cd',
        unitRighttThree: '4,561 lbs',
        unitRighttFour: 'Dual Motor',
        unitRighttFive: '250 kW',
    },
]

export default modelSItem