const modelXItem = [
    {
        img: '/images/model-s-plaid-func.jpg',
        heading: 'Model X',
        desc: 'Dual Motor All-Wheel Drive platform has the longest range, and now delivers insane power and acceleration.',
        unit1: '3.8 s',
        unit2: '348 mi',
        unit3: '670 hp',
        bottomUnit1: '0-60 mph',
        bottomUnit2: 'Range (EPA est.)',
        bottomUnit3: 'Peak Power',
    },
    {
        img: '/images/model-s-func.jpg',
        heading: 'Model X Plaid',
        desc: 'Tri Motor All-Wheel Drive platform with torque vectoring features three independent motors, each with a carbon-sleeved rotor that maintains 1,000+ horsepower all the way to top speed.',
        unit1: '2.5 s*',
        unit2: '333 mi',
        unit3: '1,020 hp',
        bottomUnit1: '0-60 mph',
        bottomUnit2: 'Range (EPA est.)',
        bottomUnit3: 'Peak Power',
    },
]

export const spec = [
    {
        headingLeftOne: 'Range (EPA est.)',
        headingLeftTwo: '1/4 Mile',
        headingLeftThree: 'Peak Power',
        headingLeftFour: 'Wheels',
        headingLeftFive: 'Towing',
        headingLeftSix: 'Seating',
        unitLeftOne: '333 mi',
        unitLeftTwo: '9.9 s',
        unitLeftThree: '1,020 hp',
        unitLeftFour: '20" or 22"',
        unitLeftFive: '5,000 lbs',
        unitLeftSix: 'Up to 6',
        headingRighttOne: '*Acceleration',
        headingRighttTwo: '†Top Speed',
        headingRighttThree: 'Drag Coefficient',
        headingRighttFour: 'Weight',
        headingRighttFive: 'Powertrain',
        headingRighttSix: 'Supercharging Max',
        unitRighttOne: '2.5 s 0-60 mph with rollout subtracted',
        unitRighttTwo: '163 mph',
        unitRighttThree: '0.24 Cd',
        unitRighttFour: '5,390 lbs',
        unitRighttFive: 'Tri Motor',
        unitRighttSix: '250 kW',
    },
    {
        headingLeftOne: 'Range (EPA est.)',
        headingLeftTwo: 'Peak Power',
        headingLeftThree: 'Wheels',
        headingLeftFour: 'Towing',
        headingLeftFive: 'Seating',
        unitLeftOne: '348 mi',
        unitLeftTwo: '670 hp',
        unitLeftThree: '20" or 22"',
        unitLeftFour: '5,000 lbs',
        unitLeftFive: 'Up to 7',
        headingRighttOne: 'Acceleration',
        headingRighttTwo: 'Top Speed',
        headingRighttThree: 'Drag Coefficient',
        headingRighttFour: 'Weight',
        headingRighttFive: 'Powertrain',
        headingRighttSix: 'Supercharging Max',
        unitRighttOne: '3.8 s 0-60 mph',
        unitRighttTwo: '155 mph',
        unitRighttThree: '0.24 Cd',
        unitRighttFour: '5,185 lbs',
        unitRighttFive: 'Dual Motor',
        unitRighttSix: '250 kW',
    },
]

export default modelXItem