const CustomOrders = [
    {
        id: 0,
        idParams: 'Model 3',
        notiDesc: 'Take delivery of a New Model 3 or Model Y in Dec 2022 for a $3,750 credit',
        estDel: 'Est. Delivery: Dec 2022',
        mi: '272',
        mph: '140',
        acceleration: '5.8',
        rearWheelDriveMi: '267',
        rearWheelDriveMph: '140',
        rearWheelDriveAcceleration: '5.8',
        allWheelDriveMi: '315',
        allWheelDriveMph: '162',
        allWheelDriveAcceleration: '3.1',
        rearWheelLabel: 'Range (EPA est.)',
        allWheelLabel: 'Range (est.)',
        // carArray: ['/images/customIntModal-3.jpg', '/images/customModal-3/white/customModal-3.jpg', '/images/customModal-3/white/customSideModal-3.jpg', '/images/customModal-3/white/customRearModal-3.jpg', '/images/customModal-3/white/customRimModal-3.jpg'],
        carArray: ['/images/customIntModal-3.jpg', '/images/customModal-3/uberWhite/uberWhiteModal-3.jpg', '/images/customModal-3/uberWhite/uberWhiteSideModal-3.jpg', '/images/customModal-3/uberWhite/uberWhiteRearModal-3.jpg', '/images/customModal-3/uberWhite/uberWhiteRimModal-3.jpg'],
        carArrayWhite: ['/images/customModal-3/white/customModal-3.jpg', '/images/customModal-3/white/customSideModal-3.jpg', '/images/customModal-3/white/customRearModal-3.jpg', '/images/customModal-3/white/customRimModal-3.jpg'],
        carArraySilver: ['/images/customModal-3/silver/customSilverModal-3.jpg', '/images/customModal-3/silver/customSilverSideModal-3.jpg', '/images/customModal-3/silver/customSilverRearModal-3.jpg', '/images/customModal-3/silver/customSilverRimModal-3.jpg'],
        carArrayBlue: ['/images/customModal-3/blue/customBlueModal-3.jpg', '/images/customModal-3/blue/customBlueSideModal-3.jpg', '/images/customModal-3/blue/customBlueRearModal-3.jpg', '/images/customModal-3/blue/customBlueRimModal-3.jpg'],
        carArrayBlack: ['/images/customModal-3/black/customBlackModal-3.jpg', '/images/customModal-3/black/customBlackSideModal-3.jpg', '/images/customModal-3/black/customBlackRearModal-3.jpg', '/images/customModal-3/black/customBlackRimModal-3.jpg'],
        carArrayRed: ['/images/customModal-3/red/customRedModal-3.jpg', '/images/customModal-3/red/customRedSideModal-3.jpg', '/images/customModal-3/red/customRedRearModal-3.jpg', '/images/customModal-3/red/customRedRimModal-3.jpg'],
        potentialSavRearWheelDrive: '$40,390*',
        potentialSavAllWheelDrive: '$56,390*',
        performanceUpgradeOne: '20’’ Übercyber Wheels',
        performanceUpgradeTwo: 'Performance Brakes',
        performanceUpgradeThree: 'Carbon fiber spoiler',
        performanceUpgradeFour: 'Aluminum alloy pedals',
        purchaseSavRearWheelDrive: '$46,990',
        purchaseSavAllWheelDrive: '$62,990',
        aeroType: 'Included',
        aeroRange: 'Range (EPA est.) : 272mi',
        aeroWheel: '18’’ Aero Wheels',
        sportWheel: '19’’ Sport Wheels',
        sportWheelPrice: '$1,500',
        sportRange: 'Range (est.) : 267mi',
        sportWheelCarArrayWhite: ['/images/customModal-3/sportWheelWhite/sportWheelWhiteModal-3.jpg', '/images/customModal-3/sportWheelWhite/sportWheelWhiteSideModal-3.jpg', '/images/customModal-3/sportWheelWhite/sportWheelWhiteRearModal-3.jpg', '/images/customModal-3/sportWheelWhite/sportWheelWhiteRimModal-3.jpg'],
        sportWheelCarArraySilver: ['/images/customModal-3/sportWheelSilver/sportWheelSilverModal-3.jpg', '/images/customModal-3/sportWheelSilver/sportWheelSilverSideModal-3.jpg', '/images/customModal-3/sportWheelSilver/sportWheelSilverRearModal-3.jpg', '/images/customModal-3/sportWheelSilver/sportWheelSilverRimModal-3.jpg'],
        sportWheelCarArrayBlue: ['/images/customModal-3/sportWheelBlue/sportWheelBlueModal-3.jpg', '/images/customModal-3/sportWheelBlue/sportWheelBlueSideModal-3.jpg', '/images/customModal-3/sportWheelBlue/sportWheelBlueRearModal-3.jpg', '/images/customModal-3/sportWheelBlue/sportWheelBlueRimModal-3.jpg'],
        sportWheelCarArrayBlack: ['/images/customModal-3/sportWheelBlack/sportWheelBlackModal-3.jpg', '/images/customModal-3/sportWheelBlack/sportWheelBlackSideModal-3.jpg', '/images/customModal-3/sportWheelBlack/sportWheelBlackRearModal-3.jpg', '/images/customModal-3/sportWheelBlack/sportWheelBlackRimModal-3.jpg'],
        sportWheelCarArrayRed: ['/images/customModal-3/sportWheelRed/sportWheelRedModal-3.jpg', '/images/customModal-3/sportWheelRed/sportWheelRedSideModal-3.jpg', '/images/customModal-3/sportWheelRed/sportWheelRedRearModal-3.jpg', '/images/customModal-3/sportWheelRed/sportWheelRedRimModal-3.jpg'],
        uberCarArrayWhite: ['/images/customModal-3/uberWhite/uberWhiteModal-3.jpg', '/images/customModal-3/uberWhite/uberWhiteSideModal-3.jpg', '/images/customModal-3/uberWhite/uberWhiteRearModal-3.jpg', '/images/customModal-3/uberWhite/uberWhiteRimModal-3.jpg'],
        uberCarArraySilver: ['/images/customModal-3/uberSilver/uberSilverModal-3.jpg', '/images/customModal-3/uberSilver/uberSilverSideModal-3.jpg', '/images/customModal-3/uberSilver/uberSilverRearModal-3.jpg', '/images/customModal-3/uberSilver/uberSilverRimModal-3.jpg'],
        uberCarArrayBlue: ['/images/customModal-3/uberBlue/uberBlueModal-3.jpg', '/images/customModal-3/uberBlue/uberBlueSideModal-3.jpg', '/images/customModal-3/uberBlue/uberBlueRearModal-3.jpg', '/images/customModal-3/uberBlue/uberBlueRimModal-3.jpg'],
        uberCarArrayBlack: ['/images/customModal-3/uberBlack/uberBlackModal-3.jpg', '/images/customModal-3/uberBlack/uberBlackSideModal-3.jpg', '/images/customModal-3/uberBlack/uberBlackRearModal-3.jpg', '/images/customModal-3/uberBlack/uberBlackRimModal-3.jpg'],
        uberCarArrayRed: ['/images/customModal-3/uberRed/uberRedModal-3.jpg', '/images/customModal-3/uberRed/uberRedSideModal-3.jpg', '/images/customModal-3/uberRed/uberRedRearModal-3.jpg', '/images/customModal-3/uberRed/uberRedRimModal-3.jpg'],
        intLabBlack: 'All Black',
        intLabBlackType: 'Included',
        intLabWhite: 'Black and White',
        intLabWhiteType: '$1,000',
        autoPilot: '$6,000',
        drivingCapaPrice: '$15,000',
        wallConnect: '$400',
        mobileConnect: '$230',
        perPrice: '$6,600',
        intItemBlack: '/images/customIntModal-3.jpg',
        intItemWhite: '/images/customIntWhiteModal-3.jpg',
        rim1: "/images/rim/rim-1.png",
        rim2: "/images/rim/rim-2.png",
        rim3: "/images/rim/rim-3.png",
        uberWheelLabel: '20’’ Übercyber Wheels',
        uberWheelLabelType: 'Included',
        carper: 'Performance',
        wheelTypeOne: 'Rear-Wheel Drive',
        wheelTypeOne: 'Dual Motor All-Wheel Drive'
    },
    {
        carArray: ['/images/customIntModal-y.jpg', '/images/customModal-y/white/customWhiteModal-y.jpg', '/images/customModal-y/white/customWhiteSideModal-y.jpg', '/images/customModal-y/white/customWhiteRearModal-y.jpg', '/images/customModal-y/white/customWhiteRimModal-y.jpg'],
        carArrayWhite: ['/images/customModal-y/white/customWhiteModal-y.jpg', '/images/customModal-y/white/customWhiteSideModal-y.jpg', '/images/customModal-y/white/customWhiteRearModal-y.jpg', '/images/customModal-y/white/customWhiteRimModal-y.jpg'],
        carArraySilver: ['/images/customModal-y/silver/customSilverModal-y.jpg', '/images/customModal-y/silver/customSilverSideModal-y.jpg', '/images/customModal-y/silver/customSilverRearModal-y.jpg', '/images/customModal-y/silver/customSilverRimModal-y.jpg'],
        carArrayBlue: ['/images/customModal-y/blue/customBlueModal-y.jpg', '/images/customModal-y/blue/customBlueSideModal-y.jpg', '/images/customModal-y/blue/customBlueRearModal-y.jpg', '/images/customModal-y/blue/customBlueRimModal-y.jpg'],
        carArrayBlack: ['/images/customModal-y/black/customBlackModal-y.jpg', '/images/customModal-y/black/customBlackSideModal-y.jpg', '/images/customModal-y/black/customBlackRearModal-y.jpg', '/images/customModal-y/black/customBlackRimModal-y.jpg'],
        carArrayRed: ['/images/customModal-y/red/customRedModal-y.jpg', '/images/customModal-y/red/customRedSideModal-y.jpg', '/images/customModal-y/red/customRedRearModal-y.jpg', '/images/customModal-y/red/customRedRimModal-y.jpg'],
        sportWheelCarArrayWhite: ['/images/customModal-y/sportWheelWhite/sportWheelWhiteModal-y.jpg', '/images/customModal-y/sportWheelWhite/sportWheelWhiteSideModal-y.jpg', '/images/customModal-y/sportWheelWhite/sportWheelWhiteRearModal-y.jpg', '/images/customModal-y/sportWheelWhite/sportWheelWhiteRimModal-y.jpg'],
        sportWheelCarArraySilver: ['/images/customModal-y/sportWheelSilver/sportWheelSilverModal-y.jpg', '/images/customModal-y/sportWheelSilver/sportWheelSilverSideModal-y.jpg', '/images/customModal-y/sportWheelSilver/sportWheelSilverRearModal-y.jpg', '/images/customModal-y/sportWheelSilver/sportWheelSilverRimModal-y.jpg'],
        sportWheelCarArrayBlue: ['/images/customModal-y/sportWheelBlue/sportWheelBlueModal-y.jpg', '/images/customModal-y/sportWheelBlue/sportWheelBlueSideModal-y.jpg', '/images/customModal-y/sportWheelBlue/sportWheelBlueRearModal-y.jpg', '/images/customModal-y/sportWheelBlue/sportWheelBlueRimModal-y.jpg'],
        sportWheelCarArrayBlack: ['/images/customModal-y/sportWheelBlack/sportWheelBlackModal-y.jpg', '/images/customModal-y/sportWheelBlack/sportWheelBlackSideModal-y.jpg', '/images/customModal-y/sportWheelBlack/sportWheelBlackRearModal-y.jpg', '/images/customModal-y/sportWheelBlack/sportWheelBlackRimModal-y.jpg'],
        sportWheelCarArrayRed: ['/images/customModal-y/sportWheelRed/sportWheelRedModal-y.jpg', '/images/customModal-y/sportWheelRed/sportWheelRedSideModal-y.jpg', '/images/customModal-y/sportWheelRed/sportWheelRedRearModal-y.jpg', '/images/customModal-y/sportWheelRed/sportWheelRedRimModal-y.jpg'],
        uberCarArrayWhite: ['/images/customModal-y/uberWhite/uberWhiteModal-y.jpg', '/images/customModal-y/uberWhite/uberWhiteSideModal-y.jpg', '/images/customModal-y/uberWhite/uberWhiteRearModal-y.jpg', '/images/customModal-y/uberWhite/uberWhiteRimModal-y.jpg'],
        uberCarArraySilver: ['/images/customModal-y/uberSilver/uberSilverModal-y.jpg', '/images/customModal-y/uberSilver/uberSilverSideModal-y.jpg', '/images/customModal-y/uberSilver/uberSilverRearModal-y.jpg', '/images/customModal-y/uberSilver/uberSilverRimModal-y.jpg'],
        uberCarArrayBlue: ['/images/customModal-y/uberBlue/uberBlueModal-y.jpg', '/images/customModal-y/uberBlue/uberBlueSideModal-y.jpg', '/images/customModal-y/uberBlue/uberBlueRearModal-y.jpg', '/images/customModal-y/uberBlue/uberBlueRimModal-y.jpg'],
        uberCarArrayBlack: ['/images/customModal-y/uberBlack/uberBlackModal-y.jpg', '/images/customModal-y/uberBlack/uberBlackSideModal-y.jpg', '/images/customModal-y/uberBlack/uberBlackRearModal-y.jpg', '/images/customModal-y/uberBlack/uberBlackRimModal-y.jpg'],
        uberCarArrayRed: ['/images/customModal-y/uberRed/uberRedModal-y.jpg', '/images/customModal-y/uberRed/uberRedSideModal-y.jpg', '/images/customModal-y/uberRed/uberRedRearModal-y.jpg', '/images/customModal-y/uberRed/uberRedRimModal-y.jpg'],
        id: 1,
        idParams: 'Model Y',
        notiDesc: 'Take delivery of a New Model 3 or Model Y in Dec 2022 for a $3,750 credit',
        estDel: 'Est. Delivery: Dec 2022 - Mar 2023',
        mi: '330',
        mph: '135',
        acceleration: '4.8',
        rearWheelDriveMi: '318',
        rearWheelDriveMph: '135',
        rearWheelDriveAcceleration: '4.8',
        allWheelDriveMi: '303',
        allWheelDriveMph: '155',
        allWheelDriveAcceleration: '3.5',
        rearWheelLabel: 'Range (EPA est.)',
        allWheelLabel: 'Range (est.)',
        performanceUpgradeOne: '21’’ Übercyber Wheels',
        incrementSpeed: 'Increased top speed from 135mph to 155mph',
        performanceUpgradeTwo: 'Performance Brakes',
        performanceUpgradeThree: 'Lowered suspension',
        performanceUpgradeFour: 'Aluminum alloy pedals',
        potentialSavRearWheelDrive: '$58,190*',
        potentialSavAllWheelDrive: '$62,190*',
        purchaseSavRearWheelDrive: '$65,990',
        purchaseSavAllWheelDrive: '$69,990',
        aeroType: 'Included',
        aeroRange: 'Range (EPA est.) : 330mi',
        sportWheelPrice: '$2,000',
        sportRange: 'Range (est.) : 318mi',
        rim1: "/images/rim/rim-4.png",
        rim2: "/images/rim/rim-5.png",
        rim3: "/images/rim/rim-3.png",
        intItemBlack: '/images/customIntModal-y.jpg',
        intItemWhite: '/images/customIntWhiteModal-y.jpg',
        intLabBlack: 'All Black',
        intLabBlackType: 'Included',
        intLabWhite: 'Black and White',
        intLabWhiteType: '$1,000',
        uberWheelLabel: '21’’ Übercyber Wheels',
        uberWheelLabelType: 'Included',
        aeroWheel: '19’’ Gemini Wheels',
        sportWheel: '20’’ Induction Wheels',
        cartype: 'Long Range',
        carper: 'Performance',
        wheelTypeOne: 'Rear-Wheel Drive',
        wheelTypeOne: 'Dual Motor All-Wheel Drive'
    },
    {
        carArray: ['/images/customIntModal-s.jpg', '/images/customModal-s/tempWheelWhite/tempWheelWhiteModal-s.jpg', '/images/customModal-s/tempWheelWhite/tempWheelWhiteSideModal-s.jpg', '/images/customModal-s/tempWheelWhite/tempWheelWhiteRearModal-s.jpg', '/images/customModal-s/tempWheelWhite/tempWheelWhiteRimModal-s.jpg'],
        carArrayWhite: ['/images/customModal-s/tempWheelWhite/tempWheelWhiteModal-s.jpg', '/images/customModal-s/tempWheelWhite/tempWheelWhiteSideModal-s.jpg', '/images/customModal-s/tempWheelWhite/tempWheelWhiteRearModal-s.jpg', '/images/customModal-s/tempWheelWhite/tempWheelWhiteRimModal-s.jpg'],
        carArraySilver: ['/images/customModal-s/tempWheelSilver/tempWheelSilverModal-s.jpg', '/images/customModal-s/tempWheelSilver/tempWheelSilverSideModal-s.jpg', '/images/customModal-s/tempWheelSilver/tempWheelSilverRearModal-s.jpg', '/images/customModal-s/tempWheelSilver/tempWheelSilverRimModal-s.jpg'],
        carArrayBlue: ['/images/customModal-s/tempWheelBlue/tempWheelBlueModal-s.jpg', '/images/customModal-s/tempWheelBlue/tempWheelBlueSideModal-s.jpg', '/images/customModal-s/tempWheelBlue/tempWheelBlueRearModal-s.jpg', '/images/customModal-s/tempWheelBlue/tempWheelBlueRimModal-s.jpg'],
        carArrayBlack: ['/images/customModal-s/tempWheelBlack/tempWheelBlackModal-s.jpg', '/images/customModal-s/tempWheelBlack/tempWheelBlackSideModal-s.jpg', '/images/customModal-s/tempWheelBlack/tempWheelBlackRearModal-s.jpg', '/images/customModal-s/tempWheelBlack/tempWheelBlackRimModal-s.jpg'],
        carArrayRed: ['/images/customModal-s/tempWheelRed/tempWheelRedModal-s.jpg', '/images/customModal-s/tempWheelRed/tempWheelRedSideModal-s.jpg', '/images/customModal-s/tempWheelRed/tempWheelRedRearModal-s.jpg', '/images/customModal-s/tempWheelRed/tempWheelRedRimModal-s.jpg'],
        sportWheelCarArrayWhite: ['/images/customModal-s/arWheelWhite/arWheelWhiteModal-s.jpg', '/images/customModal-s/arWheelWhite/arWheelWhiteSideModal-s.jpg', '/images/customModal-s/arWheelWhite/arWheelWhiteRearModal-s.jpg', '/images/customModal-s/arWheelWhite/arWheelWhiteRimModal-s.jpg'],
        sportWheelCarArraySilver: ['/images/customModal-s/arWheelSilver/arWheelSilverModal-s.jpg', '/images/customModal-s/arWheelSilver/arWheelSilverSideModal-s.jpg', '/images/customModal-s/arWheelSilver/arWheelSilverRearModal-s.jpg', '/images/customModal-s/arWheelSilver/arWheelSilverRimModal-s.jpg'],
        sportWheelCarArrayBlue: ['/images/customModal-s/arWheelBlue/arWheelBlueModal-s.jpg', '/images/customModal-s/arWheelBlue/arWheelBlueSideModal-s.jpg', '/images/customModal-s/arWheelBlue/arWheelBlueRearModal-s.jpg', '/images/customModal-s/arWheelBlue/arWheelBlueRimModal-s.jpg'],
        sportWheelCarArrayBlack: ['/images/customModal-s/arWheelBlack/arWheelBlackModal-s.jpg', '/images/customModal-s/arWheelBlack/arWheelBlackSideModal-s.jpg', '/images/customModal-s/arWheelBlack/arWheelBlackRearModal-s.jpg', '/images/customModal-s/arWheelBlack/arWheelBlackRimModal-s.jpg'],
        sportWheelCarArrayRed: ['/images/customModal-s/arWheelRed/arWheelRedModal-s.jpg', '/images/customModal-s/arWheelRed/arWheelRedSideModal-s.jpg', '/images/customModal-s/arWheelRed/arWheelRedRearModal-s.jpg', '/images/customModal-s/arWheelRed/arWheelRedRimModal-s.jpg'],
        // uberCarArrayWhite: ['/images/customModal-y/uberWhite/uberWhiteModal-y.jpg', '/images/customModal-y/uberWhite/uberWhiteSideModal-y.jpg', '/images/customModal-y/uberWhite/uberWhiteRearModal-y.jpg', '/images/customModal-y/uberWhite/uberWhiteRimModal-y.jpg'],
        // uberCarArraySilver: ['/images/customModal-y/uberSilver/uberSilverModal-y.jpg', '/images/customModal-y/uberSilver/uberSilverSideModal-y.jpg', '/images/customModal-y/uberSilver/uberSilverRearModal-y.jpg', '/images/customModal-y/uberSilver/uberSilverRimModal-y.jpg'],
        // uberCarArrayBlue: ['/images/customModal-y/uberBlue/uberBlueModal-y.jpg', '/images/customModal-y/uberBlue/uberBlueSideModal-y.jpg', '/images/customModal-y/uberBlue/uberBlueRearModal-y.jpg', '/images/customModal-y/uberBlue/uberBlueRimModal-y.jpg'],
        // uberCarArrayBlack: ['/images/customModal-y/uberBlack/uberBlackModal-y.jpg', '/images/customModal-y/uberBlack/uberBlackSideModal-y.jpg', '/images/customModal-y/uberBlack/uberBlackRearModal-y.jpg', '/images/customModal-y/uberBlack/uberBlackRimModal-y.jpg'],
        // uberCarArrayRed: ['/images/customModal-y/uberRed/uberRedModal-y.jpg', '/images/customModal-y/uberRed/uberRedSideModal-y.jpg', '/images/customModal-y/uberRed/uberRedRearModal-y.jpg', '/images/customModal-y/uberRed/uberRedRimModal-y.jpg'],
        intItemBlack: '/images/customIntModal-s.jpg',
        intItemWhite: '/images/customIntWhiteModal-s.jpg',
        intItemCream: '/images/customIntCreamModal-s.jpg',
        id: 2,
        idParams: 'Model S',
        notiDesc: 'Take delivery of a New Model 3 or Model Y in Dec 2022 for a $3,750 credit',
        estDel: 'Est. Delivery: Dec 2022',
        mi: '405',
        mph: '149',
        acceleration: '3.1',
        rearWheelDriveMi: '375',
        rearWheelDriveMph: '149',
        rearWheelDriveAcceleration: '3.1',
        allWheelDriveMi: '396',
        allWheelDriveMph: '200',
        allWheelDriveAcceleration: '1.99',
        twoAllWheelDriveMi: '348',
        twoAllWheelDriveMph: '200',
        twoAllWheelDriveAcceleration: '1.99',
        rearWheelLabel: 'Range (EPA est.)',
        performanceUpgradeOne: 'Quickest accelerating car in production today',
        performanceUpgradeTwo: '0-60 mph: 1.99s',
        performanceUpgradeThree: '1/4 mile: 9.23@155 mph trap speed',
        performanceUpgradeFour: '1,020 horsepower',
        performanceUpgradeFive: 'Three high performance motors with carbon-sleeved rotors',
        performanceUpgradeSix: 'Torque vectoring',
        allWheelLabel: 'Range (est.)',
        potentialSavRearWheelDrive: '$96,390*',
        potentialSavAllWheelDrive: '$127,390*',
        purchaseSavRearWheelDrive: '$104,990',
        purchaseSavAllWheelDrive: '$135,990',
        aeroWheel: '19" Tempest Wheels',
        aeroType: 'Included',
        aeroRange: 'Range (EPA est.) : 405mi',
        oneAeroRange: 'Range (EPA est.) : 396mi',
        sportWheel: '21" Arachnid Wheels',
        sportWheelPrice: '$4,500',
        sportRange: 'Range (EPA est.) : 375mi',
        oneSportRange: 'Range (EPA est.) : 348mi',
        perPrice: '$7,800',
        rim1: "/images/rim/rim-4.png",
        rim2: "/images/rim/rim-6.png",
        carper: 'Plaid',
        wheelTypeOne: 'Dual Motor All-Wheel Drive',
        wheelTypeTwo: 'Tri Motor All-Wheel Drive',
        intLabBlack: 'All Black',
        intLabBlackType: 'Included',
        intLabWhite: 'Black and White',
        intLabWhiteType: '$1,000',
        intLabCreamType: '$2,000',
        intLabCream: 'Cream'
    },
    {
        carArray: ['/images/customIntModal-x.jpg', '/images/customModal-x/cyberWhite/cyberWhiteModal-x.jpg', '/images/customModal-x/cyberWhite/cyberWhiteSideModal-x.jpg', '/images/customModal-x/cyberWhite/cyberWhiteRearModal-x.jpg', '/images/customModal-x/cyberWhite/cyberWhiteRimModal-x.jpg'],
        carArrayWhite: ['/images/customModal-x/cyberWhite/cyberWhiteModal-x.jpg', '/images/customModal-x/cyberWhite/cyberWhiteSideModal-x.jpg', '/images/customModal-x/cyberWhite/cyberWhiteRearModal-x.jpg', '/images/customModal-x/cyberWhite/cyberWhiteRimModal-x.jpg'],
        carArraySilver: ['/images/customModal-x/cyberSilver/cyberSilverModal-x.jpg', '/images/customModal-x/cyberSilver/cyberSilverSideModal-x.jpg', '/images/customModal-x/cyberSilver/cyberSilverRearModal-x.jpg', '/images/customModal-x/cyberSilver/cyberSilverRimModal-x.jpg'],
        carArrayBlue: ['/images/customModal-x/cyberBlue/cyberBlueModal-x.jpg', '/images/customModal-x/cyberBlue/cyberBlueSideModal-x.jpg', '/images/customModal-x/cyberBlue/cyberBlueRearModal-x.jpg', '/images/customModal-x/cyberBlue/cyberBlueRimModal-x.jpg'],
        carArrayBlack: ['/images/customModal-x/cyberBlack/cyberBlackModal-x.jpg', '/images/customModal-x/cyberBlack/cyberBlackSideModal-x.jpg', '/images/customModal-x/cyberBlack/cyberBlackRearModal-x.jpg', '/images/customModal-x/cyberBlack/cyberBlackRimModal-x.jpg'],
        carArrayRed: ['/images/customModal-x/cyberRed/cyberRedModal-x.jpg', '/images/customModal-x/cyberRed/cyberRedSideModal-x.jpg', '/images/customModal-x/cyberRed/cyberRedRearModal-x.jpg', '/images/customModal-x/cyberRed/cyberRedRimModal-x.jpg'],
        sportWheelCarArrayWhite: ['/images/customModal-x/turbineWhite/turbineWhiteModal-x.jpg', '/images/customModal-x/turbineWhite/turbineWhiteSideModal-x.jpg', '/images/customModal-x/turbineWhite/turbineWhiteRearModal-x.jpg', '/images/customModal-x/turbineWhite/turbineWhiteRimModal-x.jpg'],
        sportWheelCarArraySilver: ['/images/customModal-x/turbineSilver/turbineSilverModal-x.jpg', '/images/customModal-x/turbineSilver/turbineSilverSideModal-x.jpg', '/images/customModal-x/turbineSilver/turbineSilverRearModal-x.jpg', '/images/customModal-x/turbineSilver/turbineSilverRimModal-x.jpg'],
        sportWheelCarArrayBlue: ['/images/customModal-x/turbineBlue/turbineBlueModal-x.jpg', '/images/customModal-x/turbineBlue/turbineBlueSideModal-x.jpg', '/images/customModal-x/turbineBlue/turbineBlueRearModal-x.jpg', '/images/customModal-x/turbineBlue/turbineBlueRimModal-x.jpg'],
        sportWheelCarArrayBlack: ['/images/customModal-x/turbineBlack/turbineBlackModal-x.jpg', '/images/customModal-x/turbineBlack/turbineBlackSideModal-x.jpg', '/images/customModal-x/turbineBlack/turbineBlackRearModal-x.jpg', '/images/customModal-x/turbineBlack/turbineBlackRimModal-x.jpg'],
        sportWheelCarArrayRed: ['/images/customModal-x/turbineRed/turbineRedModal-x.jpg', '/images/customModal-x/turbineRed/turbineRedSideModal-x.jpg', '/images/customModal-x/turbineRed/turbineRedRearModal-x.jpg', '/images/customModal-x/turbineRed/turbineRedRimModal-x.jpg'],
        intItemBlack: '/images/customIntModal-x.jpg',
        intItemWhite: '/images/customIntWhiteModal-x.jpg',
        intItemCream: '/images/customIntCreamModal-x.jpg',
        rim1: "/images/rim/rim-7.png",
        rim2: "/images/rim/rim-8.png",
        performanceUpgradeOne: 'Quickest accelerating SUV in production today',
        performanceUpgradeTwo: '0-60 mph: 2.5s',
        performanceUpgradeThree: '1/4 mile: 9.9s',
        performanceUpgradeFour: '1,020 horsepower',
        performanceUpgradeFive: 'Three high performance motors with carbon-sleeved rotors',
        performanceUpgradeSix: 'Torque vectoring',
        mi: '348',
        mph: '149',
        acceleration: '3.8',
        rearWheelDriveMi: '330',
        rearWheelDriveMph: '155',
        rearWheelDriveAcceleration: '3.8',
        allWheelDriveMi: '333',
        allWheelDriveMph: '149',
        allWheelDriveAcceleration: '2.5',
        twoAllWheelDriveMi: '311',
        twoAllWheelDriveMph: '163',
        twoAllWheelDriveAcceleration: '2.5',
        id: 3,
        idParams: 'Model X',
        notiDesc: 'Take delivery of a New Model 3 or Model Y in Dec 2022 for a $3,750 credit',
        estDel: 'Est. Delivery: Dec 2022',
        rearWheelLabel: 'Range (EPA est.)',
        allWheelLabel: 'Range (est.)',
        potentialSavRearWheelDrive: '$112,590*',
        potentialSavAllWheelDrive: '$130,590*',
        purchaseSavRearWheelDrive: '$120,990',
        purchaseSavAllWheelDrive: '$138,990',
        aeroWheel: '20’’ Cyberstream Wheels',
        aeroType: 'Included',
        aeroRange: 'Range (EPA est.) : 348mi',
        oneAeroRange: 'Range (EPA est.) : 333mi',
        sportWheel: '22’’ Turbine Wheels',
        sportWheelPrice: '$5,500',
        sportRange: 'Range (est.) : 330mi',
        oneSportRange: 'Range (EPA est.) : 311mi',
        carper: 'Plaid',
        wheelTypeOne: 'Dual Motor All-Wheel Drive',
        wheelTypeTwo: 'Tri Motor All-Wheel Drive',
        intLabBlack: 'All Black',
        intLabBlackType: 'Included',
        intLabWhite: 'Black and White',
        intLabWhiteType: '$1,000',
        intLabCreamType: '$2,000',
        intLabCream: 'Cream'
    }
]

export default CustomOrders

export const paints = [
    {
        img: '/images/paint/paint-1.png',
        label: 'Pearl White Multi-Coat',
        id: 0,
        type: 'Included'
    },
    {
        img: '/images/paint/paint-2.png',
        label: 'Midnight Silver Metallic',
        id: 1,
        type: 'Included'
    },
    {
        img: '/images/paint/paint-3.png',
        label: 'Deep Blue Metallic',
        id: 2,
        type: '$1,000'
    },
    {
        img: '/images/paint/paint-4.png',
        label: 'Solid Black',
        id: 3,
        type: '$1,500'
    },
    {
        img: '/images/paint/paint-5.png',
        label: 'Red Multi-Coat',
        id: 4,
        type: '$2,000'
    }
]