const spec = [
    {
        headingLeftOne: 'Battery',
        headingLeftTwo: '*Acceleration',
        headingLeftThree: 'Range',
        headingLeftFour: 'Drive',
        headingLeftFive: 'Seating',
        headingLeftSix: 'Wheels',
        unitLeftOne: 'Long Range',
        unitLeftTwo: '3.5 s 0-60 mph with rollout subtracted',
        unitLeftThree: '303 miles (EPA est.)',
        unitLeftFour: 'Dual Motor All-Wheel Drive',
        unitLeftFive: '5 Adults',
        unitLeftSix: '21"',
        headingRighttOne: 'Weight',
        headingRighttTwo: 'Max Cargo Volume',
        headingRighttThree: 'Top Speed',
        headingRighttFour: 'Displays ',
        headingRighttFive: 'Supercharging',
        headingRighttSix: 'Warranty',
        unitRighttOne: '4,389 lbs',
        unitRighttTwo: '76 cu ft',
        unitRighttThree: '155 mph',
        unitRighttFour: '15" Center Touchscreen',
        unitRighttFive: 'Max/Payment Type 250 kW Max; Pay Per Use',
        unitRighttSix: 'Basic Vehicle - 4 years or 50,000 mi, whichever comes first',
    },
    {
        headingLeftOne: 'Battery',
        headingLeftTwo: '*Acceleration',
        headingLeftThree: 'Range',
        headingLeftFour: 'Drive',
        headingLeftFive: 'Seating',
        headingLeftSix: 'Wheels',
        unitLeftOne: 'Long Range',
        unitLeftTwo: '4.8 s 0-60 mph',
        unitLeftThree: '330 miles (EPA est.)',
        unitLeftFour: 'Dual Motor All-Wheel Drive',
        unitLeftFive: 'Up to 7',
        unitLeftSix: '19" or 20"',
        headingRighttOne: 'Weight',
        headingRighttTwo: 'Max Cargo Volume',
        headingRighttThree: 'Top Speed',
        headingRighttFour: 'Displays ',
        headingRighttFive: 'Supercharging',
        headingRighttSix: 'Warranty',
        unitRighttOne: '4,363 lbs',
        unitRighttTwo: '76 cu ft',
        unitRighttThree: '135 mph',
        unitRighttFour: '15" Center Touchscreen',
        unitRighttFive: 'Max/Payment Type 250 kW Max; Pay Per Use',
        unitRighttSix: 'Basic Vehicle - 4 years or 50,000 mi, whichever comes first',
    }
]

export default spec