const spec = [
    {
        headingLeftOne: 'Battery',
        headingLeftTwo: '*Acceleration',
        headingLeftThree: 'Range',
        headingLeftFour: 'Drive',
        headingLeftFive: 'Seating',
        headingLeftSix: 'Wheels',
        unitLeftOne: 'Long Range',
        unitLeftTwo: '3.1 s 0-60 mph with rollout subtracted',
        unitLeftThree: '315 miles (EPA est.)',
        unitLeftFour: 'Dual Motor All-Wheel Drive',
        unitLeftFive: '5 Adults',
        unitLeftSix: '20"',
        headingRighttOne: 'Weight',
        headingRighttTwo: 'Cargo',
        headingRighttThree: 'Displays',
        headingRighttFour: 'Supercharging ',
        headingRighttFive: 'Onboard Charger Max',
        headingRighttSix: 'Warranty',
        unitRighttOne: '4,048 lbs',
        unitRighttTwo: '23 cu ft',
        unitRighttThree: '15" Center Touchscreen',
        unitRighttFour: 'Max/Payment Type 250 kW Max; Pay Per Use',
        unitRighttFive: '11.5 kW max (48A)',
        unitRighttSix: 'Basic Vehicle - 4 years or 50,000 mi, whichever comes first',
    },
    {
        headingLeftOne: 'Battery',
        headingLeftTwo: '*Acceleration',
        headingLeftThree: 'Range',
        headingLeftFour: 'Drive',
        headingLeftFive: 'Seating',
        headingLeftSix: 'Wheels',
        unitLeftOne: 'Long Range',
        unitLeftTwo: '4.2 s 0-60 mph',
        unitLeftThree: '358 miles (EPA est.)',
        unitLeftFour: 'Dual Motor All-Wheel Drive',
        unitLeftFive: '5 Adults',
        unitLeftSix: '18" or 19"',
        headingRighttOne: 'Weight',
        headingRighttTwo: 'Cargo',
        headingRighttThree: 'Displays',
        headingRighttFour: 'Supercharging ',
        headingRighttFive: 'Onboard Charger Max',
        headingRighttSix: 'Warranty',
        unitRighttOne: '4,034 lbs',
        unitRighttTwo: '23 cu ft',
        unitRighttThree: '15" Center Touchscreen',
        unitRighttFour: 'Max/Payment Type 250 kW Max; Pay Per Use',
        unitRighttFive: '11.5 kW max (48A)',
        unitRighttSix: 'Basic Vehicle - 4 years or 50,000 mi, whichever comes first',
    },
    {
        headingLeftOne: 'Battery',
        headingLeftTwo: '*Acceleration',
        headingLeftThree: 'Range',
        headingLeftFour: 'Drive',
        headingLeftFive: 'Seating',
        headingLeftSix: 'Wheels',
        unitLeftOne: 'Standard Range',
        unitLeftTwo: '5.8 s 0-60 mph',
        unitLeftThree: '272 miles (EPA est.)',
        unitLeftFour: 'Rear-Wheel Drive',
        unitLeftFive: '5 Adults',
        unitLeftSix: '18" or 19"',
        headingRighttOne: 'Weight',
        headingRighttTwo: 'Cargo',
        headingRighttThree: 'Displays',
        headingRighttFour: 'Supercharging ',
        headingRighttFive: 'Onboard Charger Max',
        headingRighttSix: 'Warranty',
        unitRighttOne: '3,862 lbs',
        unitRighttTwo: '23 cu ft',
        unitRighttThree: '15" Center Touchscreen',
        unitRighttFour: 'Max/Payment Type 170 kW Max; Pay Per Use',
        unitRighttFive: '7.6 kW max (32A)',
        unitRighttSix: 'Basic Vehicle - 4 years or 50,000 mi, whichever comes first',
    },
]

export default spec